table inet captive {
    set auth_clients {
        type ipv4_addr
        flags dynamic,timeout
        timeout 40h
    }
    # NAT PREROUTING — DNS redirect
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;

        # authenticated clients bypass redirect
        iifname { "eth0", "eth1" } ip saddr @auth_clients udp dport 53 counter return
        iifname { "eth0", "eth1" } ip saddr @auth_clients tcp dport 53 counter return
        # redirect DNS for unauthenticated clients
        iifname { "eth0", "eth1" } udp dport 53 counter redirect to :5353
        iifname { "eth0", "eth1" } tcp dport 53 counter redirect to :5353
    }

    chain input {
        type filter hook input priority 0; policy drop;

        ct state established,related accept
        iif lo accept
        # allow DNS
        iifname { "eth0", "eth1" } udp dport 53 counter accept
        iifname { "eth0", "eth1" } tcp dport 53 counter accept

        tcp dport 22 accept
        udp dport 67 accept
        tcp dport 3000 accept
        tcp dport 443 accept
        tcp dport 80 accept
        ip protocol icmp accept

        # captive DNS
        iifname { "eth0", "eth1" } udp dport 5353 accept
        iifname { "eth0", "eth1" } tcp dport 5353 accept
    }

    chain forward {
        type filter hook forward priority 0; policy drop;

        ct state established,related accept
        # allow authenticated clients
        iifname { "eth0", "eth1" } ip saddr @auth_clients accept
    }
}
