nft add element inet captive auth_clients {10.40.13.45 timeout 400h}
nft add element inet captive auth_clients {10.40.13.169 timeout 400h}
nft add element inet captive auth_clients {10.40.13.205 timeout 400h}
nft add element inet captive auth_clients {10.40.13.48 timeout 40h}
nft add element inet captive auth_clients {10.40.13.51 timeout 40h}
nft add element inet captive auth_clients {10.40.13.64 timeout 40h}
nft add element inet captive auth_clients {10.40.13.72 timeout 40h} 
nft add element inet captive auth_clients {10.40.13.95 timeout 40h}
nft add element inet captive auth_clients {10.40.13.103 timeout 40h}
nft add element inet captive auth_clients {10.40.13.105 timeout 400h}
nft add element inet captive auth_clients {10.40.13.106 timeout 40h}
nft add element inet captive auth_clients {10.40.13.109 timeout 40h}
nft add element inet captive auth_clients {10.40.13.115 timeout 40h} 
nft add element inet captive auth_clients {10.40.13.116 timeout 40h} 
nft add element inet captive auth_clients {10.40.13.117 timeout 40h}
nft add element inet captive auth_clients {10.40.13.127 timeout 40h}
nft add element inet captive auth_clients {10.40.13.129 timeout 400h}
nft add element inet captive auth_clients {10.40.13.142 timeout 40h}
nft add element inet captive auth_clients {10.40.13.151 timeout 40h}
nft add element inet captive auth_clients {10.40.13.165 timeout 40h}
nft add element inet captive auth_clients {10.40.13.174 timeout 40h}
nft add element inet captive auth_clients {10.40.13.176 timeout 40h}
nft add element inet captive auth_clients {10.40.13.181 timeout 40h}
nft add element inet captive auth_clients {10.40.13.183 timeout 400h}
nft add element inet captive auth_clients {10.40.13.195 timeout 40h}
nft add element inet captive auth_clients {10.40.13.221 timeout 40h}
nft add element inet captive auth_clients {10.12.30.0/24 timeout 40h }
